<?php
namespace App\Console\Commands;
use App\Models\{ProgramType,CertificateTemplate,CustomFieldDefinition,CustomFieldValue,ReferenceCatalog,ReferenceGroup,ReferenceValue,ResourceLibrary,PracticeCycle,PracticeTask,FinalWorkDefinition,FinalWorkTheme,Instructor,InstructorProgram,InstructorSlot,Survey,SurveyField,SurveyResponse,MailingAddress,News,Testimonial,Program,User};
use Illuminate\Console\Command;use Illuminate\Support\Facades\DB;
class ImportLegacyAdminParity extends Command {
 protected $signature='legacy:import-admin {--dry-run}'; protected $description='Import legacy admin/business configuration without test question content';
 public function handle(): int {$db=DB::connection('legacy');$s=$db->getSchemaBuilder();$tables=['tm_spec_type','tm_sert','tm_spec_dop','tm_spec_zn','tm_typsv','tm_user_sv','tm_string_array_razdel','tm_string_array_grupp','tm_string_array','tm_teg','tm_docs','tm_doc_spec','tm_media','tm_media_spec','tm_pract','tm_pract_temy','tm_pract_temy_file','tm_spec_pract','tm_irab_spec','tm_irab_tem','tm_irab_def_sp','tm_prepod','tm_prepod_spec','tm_nmo_prepod_spec','tm_nmo_prepod_dat','tm_typsv_name','tm_typsv_konf','tm_typsv_konf_user','tm_addr_otprav','tm_news','tm_otziv'];foreach($tables as $t)$this->line(($s->hasTable($t)?'[+] ':'[-] ').$t);$this->warn('tm_test and question/answer content are intentionally not imported.');if($this->option('dry-run'))return self::SUCCESS;
  $programs=Program::whereNotNull('legacy_id')->pluck('id','legacy_id');$users=User::whereNotNull('legacy_id')->pluck('id','legacy_id');
  if($s->hasTable('tm_spec_type'))foreach($db->table('tm_spec_type')->get() as $r)ProgramType::updateOrCreate(['legacy_id'=>$r->num],['name'=>$r->nazv]);
  if($s->hasTable('tm_sert'))foreach($db->table('tm_sert')->get() as $r)CertificateTemplate::updateOrCreate(['legacy_id'=>$r->num],['name'=>$r->nazv,'template'=>$r->path??null]);
  if($s->hasTable('tm_spec_dop'))foreach($db->table('tm_spec_dop')->get() as $r)CustomFieldDefinition::updateOrCreate(['scope'=>'program','legacy_id'=>$r->num],['name'=>$r->nazv,'type'=>((int)($r->type??0)===1?'textarea':'text')]);
  if($s->hasTable('tm_typsv'))foreach($db->table('tm_typsv')->get() as $r)CustomFieldDefinition::updateOrCreate(['scope'=>'user','legacy_id'=>$r->num],['name'=>$r->nazv,'type'=>[0=>'text',1=>'number',2=>'date',3=>'file'][(int)$r->typ]??'text','searchable'=>(bool)($r->poi??0)]);
  $defs=CustomFieldDefinition::whereNotNull('legacy_id')->get()->groupBy('scope')->map(fn($x)=>$x->pluck('id','legacy_id'));
  if($s->hasTable('tm_spec_zn'))foreach($db->table('tm_spec_zn')->get() as $r)if(isset($programs[$r->spec],$defs['program'][$r->spec_dop]))CustomFieldValue::updateOrCreate(['definition_id'=>$defs['program'][$r->spec_dop],'entity_type'=>Program::class,'entity_id'=>$programs[$r->spec]],['value'=>$r->znach]);
  if($s->hasTable('tm_user_sv'))foreach($db->table('tm_user_sv')->get() as $r)if(isset($users[$r->inn],$defs['user'][$r->tm_typsv]))CustomFieldValue::updateOrCreate(['definition_id'=>$defs['user'][$r->tm_typsv],'entity_type'=>User::class,'entity_id'=>$users[$r->inn]],['value'=>$r->value]);
  $catalog=ReferenceCatalog::firstOrCreate(['kind'=>'array_string','legacy_id'=>0],['name'=>'Array String']);
  if($s->hasTable('tm_string_array_grupp'))foreach($db->table('tm_string_array_grupp')->get() as $r)ReferenceGroup::updateOrCreate(['catalog_id'=>$catalog->id,'legacy_id'=>$r->num??$r->id],['name'=>$r->name??$r->nazv??('Группа '.$r->num),'is_active'=>(bool)($r->act??1)]);
  $groups=ReferenceGroup::where('catalog_id',$catalog->id)->pluck('id','legacy_id');
  if($s->hasTable('tm_string_array'))foreach($db->table('tm_string_array')->get() as $r)ReferenceValue::updateOrCreate(['catalog_id'=>$catalog->id,'legacy_id'=>$r->num??$r->id],['group_id'=>$groups[$r->grupp??0]??null,'value'=>$r->value??$r->string??$r->nazv??'','is_active'=>(bool)($r->act??1)]);
  if($s->hasTable('tm_teg')){$tags=ReferenceCatalog::firstOrCreate(['kind'=>'tag','legacy_id'=>0],['name'=>'Теги']);foreach($db->table('tm_teg')->get() as $r)ReferenceValue::updateOrCreate(['catalog_id'=>$tags->id,'legacy_id'=>$r->id],['value'=>$r->tag,'is_active'=>(bool)($r->act??1)]);}
  if($s->hasTable('tm_docs'))foreach($db->table('tm_docs')->get() as $r)ResourceLibrary::updateOrCreate(['legacy_id'=>$r->num],['title'=>$r->nazv??'Документ','type'=>match((int)($r->typ_doc??0)){1=>'internship',2=>'legal_entity',default=>'document'},'file_path'=>isset($r->path)&&!preg_match('~^https?://~',$r->path)?$r->path:null,'external_url'=>isset($r->path)&&preg_match('~^https?://~',$r->path)?$r->path:null,'image_path'=>$r->img??null,'comment'=>$r->comment??null,'dated_at'=>$r->dat??null]);
  if($s->hasTable('tm_media'))foreach($db->table('tm_media')->get() as $r)ResourceLibrary::updateOrCreate(['legacy_id'=>100000000+(int)$r->num],['title'=>$r->nazv??'Медиа','type'=>[0=>'video',1=>'audio',2=>'book'][(int)($r->spec??0)]??'media','external_url'=>$r->path??null]);
  if($s->hasTable('tm_pract'))foreach($db->table('tm_pract')->get() as $r)PracticeCycle::updateOrCreate(['legacy_id'=>$r->num],['title'=>$r->nazv??('Практика '.$r->num),'description'=>$r->comment??null]);$cycles=PracticeCycle::whereNotNull('legacy_id')->pluck('id','legacy_id');
  if($s->hasTable('tm_pract_temy'))foreach($db->table('tm_pract_temy')->get() as $r)if(isset($cycles[$r->inn]))PracticeTask::updateOrCreate(['legacy_id'=>$r->num],['practice_cycle_id'=>$cycles[$r->inn],'title'=>$r->nazv??('Задание '.$r->num),'body'=>$r->zad??$r->text??null,'response_type'=>[0=>'text',1=>'file',2=>'screenshot',3=>'text_file',4=>'text_screenshot',5=>'file_screenshot',6=>'all'][(int)($r->ball??0)]??'text']);
  if($s->hasTable('tm_irab_spec'))foreach($db->table('tm_irab_spec')->get() as $r)FinalWorkDefinition::updateOrCreate(['legacy_id'=>$r->num],['title'=>$r->spec??$r->nazv??('Работа '.$r->num),'level'=>((int)($r->urov??0)===1?'final':'intermediate')]);$fd=FinalWorkDefinition::whereNotNull('legacy_id')->pluck('id','legacy_id');
  if($s->hasTable('tm_irab_tem'))foreach($db->table('tm_irab_tem')->get() as $r)if(isset($fd[$r->inn]))FinalWorkTheme::updateOrCreate(['legacy_id'=>$r->num],['definition_id'=>$fd[$r->inn],'title'=>$r->nazv]);
  if($s->hasTable('tm_prepod'))foreach($db->table('tm_prepod')->get() as $r)Instructor::updateOrCreate(['legacy_id'=>$r->num],['full_name'=>$r->fio,'bio'=>$r->text??null,'photo'=>$r->img??null,'phone'=>$r->tel??null,'email'=>$r->mail??null]);$ins=Instructor::whereNotNull('legacy_id')->pluck('id','legacy_id');
  if($s->hasTable('tm_nmo_prepod_spec'))foreach($db->table('tm_nmo_prepod_spec')->get() as $r)if(isset($ins[$r->prepod],$programs[$r->spec]))InstructorProgram::updateOrCreate(['legacy_id'=>$r->num],['instructor_id'=>$ins[$r->prepod],'program_id'=>$programs[$r->spec],'subject'=>$r->predmet??null,'sessions_per_student'=>$r->kol_raz??null,'comment'=>$r->comment??null]);$ips=InstructorProgram::whereNotNull('legacy_id')->pluck('id','legacy_id');
  if($s->hasTable('tm_nmo_prepod_dat'))foreach($db->table('tm_nmo_prepod_dat')->get() as $r)if(isset($ips[$r->nmo_prepod_spec]))InstructorSlot::updateOrCreate(['legacy_id'=>$r->num],['instructor_program_id'=>$ips[$r->nmo_prepod_spec],'date'=>$r->dat,'time'=>$r->time??null,'capacity'=>$r->vm_chel??null,'lesson_number'=>$r->nomer_zan??null,'comment'=>$r->comment??null]);
  if($s->hasTable('tm_typsv_name'))foreach($db->table('tm_typsv_name')->get() as $r)Survey::updateOrCreate(['legacy_id'=>$r->num],['title'=>$r->name]);$surveys=Survey::whereNotNull('legacy_id')->pluck('id','legacy_id');
  if($s->hasTable('tm_typsv_konf'))foreach($db->table('tm_typsv_konf')->get() as $r)if(isset($surveys[$r->konf]))SurveyField::updateOrCreate(['legacy_id'=>$r->num],['survey_id'=>$surveys[$r->konf],'title'=>$r->nazv,'type'=>[0=>'text',1=>'date',2=>'number',3=>'file',4=>'list'][(int)$r->typ]??'text','searchable'=>(bool)($r->poi??0),'position'=>$r->polosh??0,'options'=>isset($r->list)?preg_split('/\R/',trim($r->list)):null]);
  if($s->hasTable('tm_addr_otprav'))foreach($db->table('tm_addr_otprav')->get() as $r)if(isset($users[$r->inn]))MailingAddress::updateOrCreate(['user_id'=>$users[$r->inn]],['last_name'=>$r->Fam??null,'first_name'=>$r->Name??null,'middle_name'=>$r->Otch??null,'postal_code'=>$r->ind??null,'region'=>$r->oblast??null,'district'=>$r->rayon??null,'city'=>$r->gorod??null,'street'=>$r->ulica??null,'house'=>$r->dom??null,'apartment'=>$r->kv??null,'comment'=>$r->comment??null]);
  if($s->hasTable('tm_news'))foreach($db->table('tm_news')->get() as $r)News::updateOrCreate(['legacy_id'=>$r->num],['title'=>$r->nazv,'body'=>htmlspecialchars_decode($r->content??''),'image'=>$r->img??null,'published_at'=>$r->dat??null]);
  if($s->hasTable('tm_otziv'))foreach($db->table('tm_otziv')->get() as $r)Testimonial::updateOrCreate(['legacy_id'=>$r->num],['author'=>$r->fio??$r->name??'Без имени','body'=>$r->comment??'','image'=>$r->img??null,'dated_at'=>$r->dat??null]);
  $this->info('Legacy admin configuration imported; test-bank content skipped.');return self::SUCCESS; }
}
