@extends('layouts.app')
@section('title',$section->title)
@section('page-title','Учебный раздел')
@section('content')
<div class="page-heading"><div><a class="back-link" href="{{ route('learning.index') }}">← Все разделы</a><h1>{{ $section->title }}</h1><p>{{ $section->description }}</p></div><div class="badge-soft">{{ number_format((float)$progress->progress_percent,0) }}% пройдено</div></div>
<div class="panel"><div class="panel-head"><h2>Материалы</h2></div>@forelse($section->contentItems as $item)<article class="content-item"><div class="content-icon">{{ strtoupper(substr($item->type ?? 'M',0,2)) }}</div><div><h3>{{ $item->title }}</h3>@if($item->body)<div class="content-body">{!! $item->body !!}</div>@endif @if($item->file_path)<a href="{{ route('learning.download',$item) }}">Скачать материал</a>@endif @if($item->external_url)<a target="_blank" rel="noopener" href="{{ $item->external_url }}">Открыть ресурс ↗</a>@endif</div></article>@empty<p class="empty">Материалы пока не добавлены или сейчас недоступны.</p>@endforelse</div>
@if($quizzes->isNotEmpty())<div class="panel mt-4"><div class="panel-head"><h2>Тесты раздела</h2></div>@foreach($quizzes as $quiz) @php($last=$quizAttempts->get($quiz->id)?->first()) <div class="list-row"><div><strong>{{ $quiz->title }}</strong><small>Проходной балл {{ $quiz->pass_percent }}%@if($last) · последняя попытка {{ number_format($last->percent,0) }}%@endif</small></div><a class="btn btn-sm btn-primary" href="{{ route('quizzes.show',$quiz) }}">{{ $last?'Повторить':'Пройти' }}</a></div>@endforeach</div>@endif
@if($practice->isNotEmpty())<div class="panel mt-4"><div class="panel-head"><h2>Практические задания</h2></div>@foreach($practice as $a) @php($submission=$submissions->get($a->id)) <div class="list-row"><div><strong>{{ $a->title }}</strong><small>{{ $submission?->status ?: 'не отправлено' }}@if($a->ends_at) · срок {{ $a->ends_at->format('d.m.Y') }}@endif</small></div><a class="btn btn-sm btn-primary" href="{{ route('practice.index') }}">Открыть</a></div>@endforeach</div>@endif
@if(!$progress->completed_at)<form class="mt-3" method="post" action="{{ route('learning.complete',$section) }}">@csrf<button class="btn btn-success">Отметить раздел пройденным</button></form>@else<div class="alert alert-success mt-3">Раздел завершён {{ $progress->completed_at->format('d.m.Y H:i') }}.</div>@endif
@endsection
