@extends('layouts.public')
@section('title','Дополнительное профессиональное образование · ГАПОУ ЗМК')
@section('content')
<section class="hero-modern"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-7"><span class="hero-kicker">Дополнительное профессиональное образование</span><h1>Обучение медицинских специалистов без лишней бюрократии</h1><p>Повышение квалификации, НМО, практические циклы и итоговая аттестация в единой цифровой системе — от выбора программы до документов об обучении.</p><div class="d-flex gap-3 flex-wrap mt-4"><a class="btn btn-primary btn-lg" href="{{route('public.programs')}}">Посмотреть программы</a>@guest<a class="btn btn-light btn-lg border" href="{{route('login')}}">Войти в личный кабинет</a>@endguest</div></div><div class="col-lg-5"><div class="hero-panel"><h4>Что доступно в системе</h4><div class="row g-3 mt-1"><div class="col-6"><div class="metric"><strong>{{number_format($featured->count())}}+</strong><span>актуальных направлений</span></div></div><div class="col-6"><div class="metric"><strong>ДПО</strong><span>и НМО в одном кабинете</span></div></div><div class="col-12"><div class="metric"><strong>Полный цикл</strong><span>материалы, тесты, практики, куратор, итоговые работы и документы</span></div></div></div></div></div></div></div></section>

<section class="section-block" id="about"><div class="container"><div class="section-title"><span class="text-primary fw-bold">ОБ ОТДЕЛЕНИИ</span><h2>Сохранили весь учебный процесс, но сделали его современным</h2><p class="text-secondary">Смысл старой системы остаётся прежним: слушатель выбирает программу, обучается по разделам, проходит контроль, взаимодействует с куратором и завершает цикл. Теперь это собрано в понятном интерфейсе.</p></div><div class="row g-3">@forelse($categories as $c)<div class="col-md-6 col-lg-3"><a class="category-chip" href="{{route('public.programs',['category'=>$c->category])}}"><span>{{$c->category}}</span><b>{{$c->total}}</b></a></div>@empty<div class="col-12 text-secondary">Категории появятся после импорта программ.</div>@endforelse</div></div></section>

<section class="section-block bg-white"><div class="container"><div class="d-flex justify-content-between align-items-end gap-3 mb-4"><div class="section-title mb-0"><span class="text-primary fw-bold">ПРОГРАММЫ</span><h2>Актуальные курсы и циклы</h2></div><a href="{{route('public.programs')}}" class="btn btn-outline-primary">Все программы</a></div><div class="row g-4">@forelse($featured as $p)<div class="col-md-6 col-lg-4"><article class="course-card"><a href="{{route('public.program',$p)}}"><div class="course-image">@if($p->image)<img src="{{asset('timg/'.$p->image)}}" alt="{{$p->title}}">@else<span class="display-5">✚</span>@endif</div><div class="course-body"><div class="course-meta">@if($p->category)<span class="pill">{{$p->category}}</span>@endif<span class="pill">{{strtoupper($p->mode)}}</span>@if($p->hours)<span class="pill">{{$p->hours}} ч.</span>@endif</div><h3>{{$p->title}}</h3><div class="d-flex justify-content-between align-items-center mt-3"><span class="text-secondary">{{$p->starts_at?->format('d.m.Y')??'Дата по набору'}}</span>@if($p->price!==null)<strong>{{number_format((float)$p->price,0,',',' ')}} ₽</strong>@endif</div></div></a></article></div>@empty<div class="col-12"><div class="news-card text-secondary">После импорта здесь появятся активные программы.</div></div>@endforelse</div></div></section>

<section class="section-block" id="news"><div class="container"><div class="section-title"><span class="text-primary fw-bold">НОВОСТИ</span><h2>Что происходит в отделении</h2></div><div class="row g-4">@forelse($news as $item)<div class="col-md-6 col-lg-4"><article class="news-card"><small class="text-secondary">{{$item->published_at?->format('d.m.Y')}}</small><h4 class="mt-2">{{$item->title}}</h4><div class="text-secondary">{{\Illuminate\Support\Str::limit(strip_tags($item->body),220)}}</div></article></div>@empty<div class="col-12 text-secondary">Новостей пока нет.</div>@endforelse</div></div></section>

@if($testimonials->isNotEmpty())<section class="section-block bg-white"><div class="container"><div class="section-title"><span class="text-primary fw-bold">ОТЗЫВЫ</span><h2>Отзывы слушателей</h2></div><div class="row g-4">@foreach($testimonials as $item)<div class="col-md-6 col-lg-4"><div class="testimonial-card"><p>«{{$item->body}}»</p><strong>{{$item->author}}</strong></div></div>@endforeach</div></div></section>@endif
@endsection
