<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('programs',function(Blueprint $t){$t->id();$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('title');$t->date('starts_at')->nullable();$t->date('ends_at')->nullable();$t->string('image')->nullable();$t->boolean('is_active')->default(true);$t->string('mode',20)->default('dpo');$t->unsignedInteger('hours')->nullable();$t->timestamps();});
Schema::create('groups',function(Blueprint $t){$t->id();$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('name');$t->timestamps();});
Schema::create('enrollments',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('program_id')->constrained()->cascadeOnDelete();$t->foreignId('group_id')->nullable()->constrained('groups')->nullOnDelete();$t->unsignedBigInteger('legacy_user_id')->nullable();$t->string('status',20)->default('active');$t->date('started_at')->nullable();$t->date('completed_at')->nullable();$t->timestamps();$t->unique(['user_id','program_id']);});
Schema::create('learning_sections',function(Blueprint $t){$t->id();$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('program_id')->constrained()->cascadeOnDelete();$t->foreignId('parent_id')->nullable()->constrained('learning_sections')->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->string('type',30)->default('material');$t->unsignedInteger('position')->default(0);$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('content_items',function(Blueprint $t){$t->id();$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('learning_section_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('type',30)->default('html');$t->longText('body')->nullable();$t->string('file_path')->nullable();$t->string('external_url')->nullable();$t->unsignedInteger('position')->default(0);$t->boolean('is_required')->default(true);$t->timestamps();});
Schema::create('section_progress',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('learning_section_id')->constrained()->cascadeOnDelete();$t->decimal('progress_percent',5,2)->default(0);$t->timestamp('completed_at')->nullable();$t->json('meta')->nullable();$t->timestamps();$t->unique(['user_id','learning_section_id']);});
} public function down(): void {foreach(['section_progress','content_items','learning_sections','enrollments','groups','programs'] as $table) Schema::dropIfExists($table);} };
