<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('program_types',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('name');}));
  Schema::create('certificate_templates',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('name');$t->string('template')->nullable();$t->boolean('is_active')->default(true);}));
  Schema::table('programs',function(Blueprint $t){$t->foreignId('program_type_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('certificate_template_id')->nullable()->constrained()->nullOnDelete();$t->longText('about')->nullable();$t->boolean('registration_enabled')->default(true);$t->boolean('featured')->default(false);$t->json('settings')->nullable();});
  Schema::table('users',function(Blueprint $t){$t->foreignId('parent_user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('subgroup')->nullable()->index();$t->timestamp('registration_confirmed_at')->nullable();$t->string('phone')->nullable();});
  Schema::table('enrollments',function(Blueprint $t){$t->boolean('is_paid')->default(false);$t->date('paid_at')->nullable();$t->string('shipment_tracking')->nullable();$t->timestamp('shipment_notified_at')->nullable();});
  Schema::table('content_items',function(Blueprint $t){$t->dateTime('available_from')->nullable();$t->dateTime('available_until')->nullable();$t->json('settings')->nullable();$t->string('response_type',30)->nullable();$t->unsignedInteger('repeat_limit')->nullable();});
  Schema::create('custom_field_definitions',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->string('scope',20);$t->string('name');$t->string('type',20)->default('text');$t->boolean('searchable')->default(false);$t->unsignedInteger('position')->default(0);$t->json('options')->nullable();$t->boolean('is_active')->default(true);}));
  Schema::create('custom_field_values',fn(Blueprint $t)=>$this->base($t,function($t){$t->foreignId('definition_id')->constrained('custom_field_definitions')->cascadeOnDelete();$t->morphs('entity');$t->longText('value')->nullable();$t->unique(['definition_id','entity_type','entity_id'],'custom_value_unique');}));
  Schema::create('reference_catalogs',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->string('kind',30)->default('generic');$t->string('name');$t->boolean('is_active')->default(true);}));
  Schema::create('reference_groups',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('catalog_id')->constrained('reference_catalogs')->cascadeOnDelete();$t->string('name');$t->boolean('is_active')->default(true);}));
  Schema::create('reference_values',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('catalog_id')->constrained('reference_catalogs')->cascadeOnDelete();$t->foreignId('group_id')->nullable()->constrained('reference_groups')->nullOnDelete();$t->text('value');$t->boolean('is_active')->default(true);$t->unsignedInteger('position')->default(0);}));
  Schema::create('resource_library',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->string('title');$t->string('type',30)->default('document');$t->string('file_path')->nullable();$t->string('external_url')->nullable();$t->string('image_path')->nullable();$t->text('comment')->nullable();$t->date('dated_at')->nullable();$t->json('settings')->nullable();$t->boolean('is_active')->default(true);}));
  Schema::create('program_resource',function(Blueprint $t){$t->id();$t->foreignId('program_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('resource_id')->constrained('resource_library')->cascadeOnDelete();$t->string('section')->nullable();$t->timestamps();$t->unique(['program_id','resource_id']);});
  Schema::create('practice_cycles',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('title');$t->text('description')->nullable();$t->boolean('is_active')->default(true);}));
  Schema::create('practice_tasks',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('practice_cycle_id')->constrained()->cascadeOnDelete();$t->string('title');$t->longText('body')->nullable();$t->string('response_type',30)->default('text');$t->unsignedInteger('position')->default(0);$t->json('attachments')->nullable();}));
  Schema::create('practice_cycle_program',function(Blueprint $t){$t->id();$t->foreignId('practice_cycle_id')->constrained()->cascadeOnDelete();$t->foreignId('program_id')->constrained()->cascadeOnDelete();$t->date('starts_at')->nullable();$t->date('ends_at')->nullable();$t->timestamps();$t->unique(['practice_cycle_id','program_id']);});
  Schema::create('final_work_definitions',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('title');$t->string('level',20)->default('final');$t->boolean('is_active')->default(true);}));
  Schema::create('final_work_themes',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('definition_id')->constrained('final_work_definitions')->cascadeOnDelete();$t->text('title');$t->boolean('is_active')->default(true);}));
  Schema::create('final_work_program',function(Blueprint $t){$t->id();$t->foreignId('definition_id')->constrained('final_work_definitions')->cascadeOnDelete();$t->foreignId('program_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['definition_id','program_id']);});
  Schema::create('instructors',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('full_name');$t->text('bio')->nullable();$t->string('photo')->nullable();$t->string('phone')->nullable();$t->string('email')->nullable();$t->boolean('is_active')->default(true);}));
  Schema::create('instructor_program',function(Blueprint $t){$t->id();$t->foreignId('instructor_id')->constrained()->cascadeOnDelete();$t->foreignId('program_id')->nullable()->constrained()->cascadeOnDelete();$t->string('subject')->nullable();$t->unsignedInteger('sessions_per_student')->nullable();$t->text('comment')->nullable();$t->timestamps();});
  Schema::create('instructor_slots',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('instructor_program_id')->constrained('instructor_program')->cascadeOnDelete();$t->date('date');$t->time('time')->nullable();$t->unsignedInteger('capacity')->nullable();$t->unsignedInteger('lesson_number')->nullable();$t->text('comment')->nullable();}));
  Schema::create('instructor_slot_user',function(Blueprint $t){$t->id();$t->foreignId('slot_id')->constrained('instructor_slots')->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->timestamps();$t->unique(['slot_id','user_id']);});
  Schema::create('surveys',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('title');$t->boolean('is_active')->default(true);}));
  Schema::create('survey_fields',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('survey_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('type',20)->default('text');$t->boolean('searchable')->default(false);$t->unsignedInteger('position')->default(0);$t->json('options')->nullable();}));
  Schema::create('survey_responses',fn(Blueprint $t)=>$this->base($t,function($t){$t->foreignId('survey_field_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->longText('value')->nullable();$t->string('file_path')->nullable();$t->unique(['survey_field_id','user_id']);}));
  Schema::create('mailing_addresses',fn(Blueprint $t)=>$this->base($t,function($t){$t->foreignId('user_id')->constrained()->cascadeOnDelete()->unique();$t->string('last_name')->nullable();$t->string('first_name')->nullable();$t->string('middle_name')->nullable();$t->string('postal_code')->nullable();$t->string('region')->nullable();$t->string('district')->nullable();$t->string('city')->nullable();$t->string('street')->nullable();$t->string('house')->nullable();$t->string('apartment')->nullable();$t->text('comment')->nullable();}));
  Schema::create('quiz_user_overrides',fn(Blueprint $t)=>$this->base($t,function($t){$t->foreignId('quiz_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->dateTime('available_from')->nullable();$t->dateTime('available_until')->nullable();$t->unsignedInteger('attempt_limit')->nullable();$t->text('reason')->nullable();$t->foreignId('changed_by')->nullable()->constrained('users')->nullOnDelete();$t->unique(['quiz_id','user_id']);}));
  Schema::create('admin_permissions',fn(Blueprint $t)=>$this->base($t,function($t){$t->string('key')->unique();$t->string('name');$t->string('group')->nullable();}));
  Schema::create('admin_permission_user',function(Blueprint $t){$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('permission_id')->constrained('admin_permissions')->cascadeOnDelete();$t->primary(['user_id','permission_id']);});
  Schema::create('app_settings',fn(Blueprint $t)=>$this->base($t,function($t){$t->string('key')->unique();$t->longText('value')->nullable();$t->string('type',20)->default('string');}));
  Schema::create('audit_logs',fn(Blueprint $t)=>$this->base($t,function($t){$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('entity_type')->nullable();$t->unsignedBigInteger('entity_id')->nullable();$t->json('before')->nullable();$t->json('after')->nullable();$t->string('ip',45)->nullable();}));
  Schema::create('news',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('title');$t->longText('body');$t->string('image')->nullable();$t->date('published_at')->nullable();$t->boolean('is_active')->default(true);}));
  Schema::create('testimonials',fn(Blueprint $t)=>$this->base($t,function($t){$t->unsignedBigInteger('legacy_id')->nullable()->unique();$t->string('author');$t->text('body');$t->string('image')->nullable();$t->date('dated_at')->nullable();$t->boolean('is_active')->default(true);}));
 }
 private function base(Blueprint $t, callable $cb): void {$t->id();$cb($t);$t->timestamps();}
 public function down(): void {foreach(['testimonials','news','audit_logs','app_settings','admin_permission_user','admin_permissions','quiz_user_overrides','mailing_addresses','survey_responses','survey_fields','surveys','instructor_slot_user','instructor_slots','instructor_program','instructors','final_work_program','final_work_themes','final_work_definitions','practice_cycle_program','practice_tasks','practice_cycles','program_resource','resource_library','reference_values','reference_groups','reference_catalogs','custom_field_values','custom_field_definitions','certificate_templates','program_types'] as $x)Schema::dropIfExists($x);Schema::table('content_items',fn(Blueprint $t)=>$t->dropColumn(['available_from','available_until','settings','response_type','repeat_limit']));Schema::table('enrollments',fn(Blueprint $t)=>$t->dropColumn(['is_paid','paid_at','shipment_tracking','shipment_notified_at']));Schema::table('users',function(Blueprint $t){$t->dropForeign(['parent_user_id']);$t->dropColumn(['parent_user_id','subgroup','registration_confirmed_at','phone']);});Schema::table('programs',function(Blueprint $t){$t->dropForeign(['program_type_id']);$t->dropForeign(['certificate_template_id']);$t->dropColumn(['program_type_id','certificate_template_id','about','registration_enabled','featured','settings']);});}
};