<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up(): void {
Schema::create('quizzes',function(Blueprint $t){$t->id();$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('program_id')->nullable()->constrained()->cascadeOnDelete();$t->foreignId('learning_section_id')->nullable()->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->unsignedTinyInteger('pass_percent')->default(70);$t->unsignedSmallInteger('attempt_limit')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('quiz_questions',function(Blueprint $t){$t->id();$t->foreignId('quiz_id')->constrained()->cascadeOnDelete();$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->text('question');$t->string('type',20)->default('single');$t->unsignedInteger('position')->default(0);$t->decimal('points',8,2)->default(1);$t->timestamps();});
Schema::create('quiz_options',function(Blueprint $t){$t->id();$t->foreignId('quiz_question_id')->constrained()->cascadeOnDelete();$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->text('text');$t->boolean('is_correct')->default(false);$t->unsignedInteger('position')->default(0);$t->timestamps();});
Schema::create('quiz_attempts',function(Blueprint $t){$t->id();$t->foreignId('quiz_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->decimal('score',10,2)->default(0);$t->decimal('percent',5,2)->default(0);$t->boolean('passed')->default(false);$t->json('answers')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('finished_at')->nullable();$t->string('ip',45)->nullable();$t->timestamps();});
Schema::create('practice_assignments',function(Blueprint $t){$t->id();$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('program_id')->constrained()->cascadeOnDelete();$t->foreignId('learning_section_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->text('description')->nullable();$t->date('starts_at')->nullable();$t->date('ends_at')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
Schema::create('submissions',function(Blueprint $t){$t->id();$t->unsignedBigInteger('legacy_id')->nullable()->index();$t->foreignId('practice_assignment_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('file_path')->nullable();$t->text('comment')->nullable();$t->text('review_comment')->nullable();$t->decimal('score',8,2)->nullable();$t->string('status',20)->default('submitted');$t->timestamp('submitted_at')->nullable();$t->timestamp('reviewed_at')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
} public function down(): void {foreach(['submissions','practice_assignments','quiz_attempts','quiz_options','quiz_questions','quizzes'] as $table) Schema::dropIfExists($table);} };
