<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\{User,Enrollment,Program,MailingAddress};use App\Services\AuditService;use Illuminate\Http\Request;use Illuminate\Support\Facades\{DB,Hash,Password};use Illuminate\Support\Str;
class BulkUserController extends Controller {
 public function create(Request $r,AuditService $audit){$d=$r->validate(['program_id'=>'required|exists:programs,id','names'=>'required|string','started_at'=>'nullable|date','subgroup'=>'nullable|max:100','parent_user_id'=>'nullable|exists:users,id']);$created=0;DB::transaction(function()use($d,&$created){foreach(preg_split('/\R/',trim($d['names'])) as $name){$name=trim($name);if(!$name)continue;$login='u'.Str::lower(Str::random(10));$u=User::create(['login'=>$login,'full_name'=>$name,'password'=>Hash::make(Str::random(24)),'role'=>'student','is_active'=>true,'subgroup'=>$d['subgroup']??null,'parent_user_id'=>$d['parent_user_id']??null]);Enrollment::create(['user_id'=>$u->id,'program_id'=>$d['program_id'],'status'=>'active','started_at'=>$d['started_at']??now()->toDateString()]);$created++;}});$audit->write('bulk_users_created',null,[],['count'=>$created,'program_id'=>$d['program_id']]);return back()->with('ok','Создано слушателей: '.$created);}
 public function transfer(Request $r,AuditService $audit){$d=$r->validate(['from_program_id'=>'required|exists:programs,id','to_program_id'=>'required|different:from_program_id|exists:programs,id']);$items=Enrollment::where('program_id',$d['from_program_id'])->get();DB::transaction(function()use($items,$d){foreach($items as $e){Enrollment::updateOrCreate(['user_id'=>$e->user_id,'program_id'=>$d['to_program_id']],['group_id'=>$e->group_id,'curator_id'=>$e->curator_id,'status'=>$e->status,'started_at'=>$e->started_at,'ends_at'=>$e->ends_at]);$e->update(['status'=>'archived']);}});$audit->write('program_bulk_transfer',null,[],['from'=>$d['from_program_id'],'to'=>$d['to_program_id'],'count'=>$items->count()]);return back()->with('ok','Переведено: '.$items->count());}
 public function state(Request $r,Enrollment $enrollment,AuditService $audit){$before=$enrollment->toArray();$d=$r->validate(['is_paid'=>'nullable|boolean','paid_at'=>'nullable|date','shipment_tracking'=>'nullable|max:255','status'=>'nullable|in:active,blocked,completed,archived']);if(array_key_exists('is_paid',$d))$d['is_paid']=$r->boolean('is_paid');$enrollment->update($d);$audit->write('enrollment_state',$enrollment,$before,$enrollment->fresh()->toArray());return back()->with('ok','Состояние слушателя обновлено');}
 public function confirm(User $user,AuditService $audit){$user->update(['registration_confirmed_at'=>now(),'is_active'=>true]);if($user->email)Password::sendResetLink(['email'=>$user->email]);$audit->write('registration_confirmed',$user);return back()->with('ok','Регистрация подтверждена. При наличии email отправлена безопасная ссылка установки пароля.');}
 public function address(Request $r,User $user){$d=$r->validate(['last_name'=>'nullable','first_name'=>'nullable','middle_name'=>'nullable','postal_code'=>'nullable','region'=>'nullable','district'=>'nullable','city'=>'nullable','street'=>'nullable','house'=>'nullable','apartment'=>'nullable','comment'=>'nullable']);MailingAddress::updateOrCreate(['user_id'=>$user->id],$d);return back()->with('ok','Почтовый адрес сохранён');}
}
