<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;use App\Models\{Program,LearningSection,ContentItem};use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class ContentAdminController extends Controller {
 public function index(Request $r){$programs=Program::orderBy('title')->get();$program=$r->filled('program_id')?Program::find($r->program_id):$programs->first();$sections=$program?LearningSection::with('contentItems')->where('program_id',$program->id)->orderBy('position')->get():collect();return view('admin.legacy.learning-content',compact('programs','program','sections'));}
 public function section(Request $r){LearningSection::create($r->validate(['program_id'=>'required|exists:programs,id','title'=>'required|max:255','description'=>'nullable','position'=>'nullable|integer|min:0'])+['type'=>'material','is_active'=>true,'is_required'=>$r->boolean('is_required')]);return back()->with('ok','Раздел создан');}
 public function item(Request $r){$d=$r->validate(['learning_section_id'=>'required|exists:learning_sections,id','title'=>'required|max:255','type'=>'required|max:40','body'=>'nullable','file_path'=>'nullable|max:500','external_url'=>'nullable|max:1000','position'=>'nullable|integer|min:0','available_from'=>'nullable|date','available_until'=>'nullable|date','repeat_limit'=>'nullable|integer|min:1','response_type'=>'nullable|max:30','settings_json'=>'nullable']);$settings=[];if(!empty($d['settings_json'])){$settings=json_decode($d['settings_json'],true);abort_if(json_last_error()!==JSON_ERROR_NONE,422,'Некорректный JSON настроек');}unset($d['settings_json']);ContentItem::create($d+['settings'=>$settings,'is_required'=>$r->boolean('is_required')]);return back()->with('ok','Элемент добавлен');}
 public function update(Request $r,ContentItem $item){$before=$item->toArray();$item->update($r->validate(['title'=>'required|max:255','position'=>'nullable|integer|min:0','available_from'=>'nullable|date','available_until'=>'nullable|date','repeat_limit'=>'nullable|integer|min:1'])+['is_required'=>$r->boolean('is_required')]);return back()->with('ok','Элемент обновлён');}
 public function copySection(Request $r,LearningSection $section){$d=$r->validate(['program_id'=>'required|exists:programs,id']);DB::transaction(function()use($section,$d){$copy=$section->replicate(['legacy_id']);$copy->program_id=$d['program_id'];$copy->title.=' (копия)';$copy->save();foreach($section->contentItems as $item){$x=$item->replicate(['legacy_id']);$x->learning_section_id=$copy->id;$x->save();}});return back()->with('ok','Раздел и его материалы скопированы');}
 public function copyItem(Request $r,ContentItem $item){$d=$r->validate(['learning_section_id'=>'required|exists:learning_sections,id']);$x=$item->replicate(['legacy_id']);$x->learning_section_id=$d['learning_section_id'];$x->title.=' (копия)';$x->save();return back()->with('ok','Материал скопирован');}
}
