<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\{ReferenceCatalog,ReferenceGroup,ReferenceValue,ResourceLibrary,PracticeCycle,PracticeTask,FinalWorkDefinition,FinalWorkTheme,Instructor,InstructorProgram,InstructorSlot,Survey,SurveyField,SurveyResponse,CustomFieldDefinition,AppSetting,News,Testimonial,Program,User,Enrollment,QuizUserOverride,AuditLog};
use App\Services\AuditService;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class LegacyAdminController extends Controller {
 public function index(){return view('admin.legacy.index',['stats'=>['catalogs'=>ReferenceCatalog::count(),'resources'=>ResourceLibrary::count(),'instructors'=>Instructor::count(),'surveys'=>Survey::count(),'practice'=>PracticeCycle::count(),'finals'=>FinalWorkDefinition::count()]]);}
 public function references(){return view('admin.legacy.references',['catalogs'=>ReferenceCatalog::with('groups','values')->orderBy('name')->get()]);}
 public function referenceStore(Request $r){$d=$r->validate(['kind'=>'required|max:30','name'=>'required|max:255','catalog_id'=>'nullable|exists:reference_catalogs,id','group_id'=>'nullable|exists:reference_groups,id','value'=>'nullable|string']);if($r->filled('value'))ReferenceValue::create(['catalog_id'=>$d['catalog_id'],'group_id'=>$d['group_id']??null,'value'=>$d['value']]);elseif($r->filled('catalog_id'))ReferenceGroup::create(['catalog_id'=>$d['catalog_id'],'name'=>$d['name']]);else ReferenceCatalog::create(['kind'=>$d['kind'],'name'=>$d['name']]);return back()->with('ok','Справочник обновлён');}
 public function resources(){return view('admin.legacy.resources',['items'=>ResourceLibrary::latest()->paginate(50),'programs'=>Program::orderBy('title')->get()]);}
 public function resourceStore(Request $r){$d=$r->validate(['title'=>'required|max:255','type'=>'required|max:30','file_path'=>'nullable|max:500','external_url'=>'nullable|url|max:1000','image_path'=>'nullable|max:500','comment'=>'nullable|string','dated_at'=>'nullable|date','program_id'=>'nullable|exists:programs,id']);$p=$d['program_id']??null;unset($d['program_id']);$x=ResourceLibrary::create($d);DB::table('program_resource')->insert(['program_id'=>$p,'resource_id'=>$x->id,'created_at'=>now(),'updated_at'=>now()]);return back()->with('ok','Материал добавлен');}
 public function practice(){return view('admin.legacy.practice',['cycles'=>PracticeCycle::with('tasks','programs')->get(),'programs'=>Program::orderBy('title')->get()]);}
 public function practiceStore(Request $r){if($r->input('entity')==='task'){PracticeTask::create($r->validate(['practice_cycle_id'=>'required|exists:practice_cycles,id','title'=>'required|max:255','body'=>'nullable|string','response_type'=>'required|in:text,file,screenshot,text_file,text_screenshot,file_screenshot,all','position'=>'nullable|integer']));}else{$c=PracticeCycle::create($r->validate(['title'=>'required|max:255','description'=>'nullable|string']));if($r->filled('program_id'))$c->programs()->attach($r->integer('program_id'),['starts_at'=>$r->input('starts_at'),'ends_at'=>$r->input('ends_at')]);}return back()->with('ok','Практика обновлена');}
 public function finals(){return view('admin.legacy.finals',['definitions'=>FinalWorkDefinition::with('themes','programs')->get(),'programs'=>Program::orderBy('title')->get()]);}
 public function finalStore(Request $r){if($r->input('entity')==='theme')FinalWorkTheme::create($r->validate(['definition_id'=>'required|exists:final_work_definitions,id','title'=>'required']));else{$d=FinalWorkDefinition::create($r->validate(['title'=>'required|max:255','level'=>'required|in:intermediate,final']));if($r->filled('program_id'))$d->programs()->attach($r->integer('program_id'));}return back()->with('ok','Итоговые работы обновлены');}
 public function instructors(){return view('admin.legacy.instructors',['items'=>Instructor::with('assignments.program','assignments.slots')->get(),'programs'=>Program::orderBy('title')->get()]);}
 public function instructorStore(Request $r){$i=Instructor::create($r->validate(['full_name'=>'required|max:255','bio'=>'nullable','phone'=>'nullable|max:50','email'=>'nullable|email']));if($r->filled('program_id'))InstructorProgram::create(['instructor_id'=>$i->id,'program_id'=>$r->integer('program_id'),'subject'=>$r->input('subject'),'sessions_per_student'=>$r->integer('sessions_per_student')?:null,'comment'=>$r->input('comment')]);return back()->with('ok','Преподаватель добавлен');}
 public function slotStore(Request $r){InstructorSlot::create($r->validate(['instructor_program_id'=>'required|exists:instructor_program,id','date'=>'required|date','time'=>'nullable','capacity'=>'nullable|integer|min:1','lesson_number'=>'nullable|integer|min:0','comment'=>'nullable']));return back()->with('ok','Слот добавлен');}
 public function surveys(){return view('admin.legacy.surveys',['items'=>Survey::with('fields')->get()]);}
 public function surveyStore(Request $r){if($r->input('entity')==='field'){SurveyField::create(['survey_id'=>$r->integer('survey_id'),'title'=>$r->string('title'),'type'=>$r->input('type','text'),'searchable'=>$r->boolean('searchable'),'position'=>$r->integer('position'),'options'=>$r->filled('options')?preg_split('/\R/',trim($r->options)):null]);}else Survey::create(['title'=>$r->validate(['title'=>'required|max:255'])['title']]);return back()->with('ok','Анкета обновлена');}
 public function surveyReport(Survey $survey){$survey->load('fields');$users=User::where('role','student')->orderBy('full_name')->get();$responses=SurveyResponse::whereIn('survey_field_id',$survey->fields->pluck('id'))->get()->keyBy(fn($x)=>$x->user_id.'-'.$x->survey_field_id);return view('admin.legacy.survey-report',compact('survey','users','responses'));}
 public function customFields(){return view('admin.legacy.custom-fields',['items'=>CustomFieldDefinition::orderBy('scope')->orderBy('position')->get()]);}
 public function customFieldStore(Request $r){CustomFieldDefinition::create(['scope'=>$r->validate(['scope'=>'required|in:user,program'])['scope'],'name'=>$r->validate(['name'=>'required|max:255'])['name'],'type'=>$r->input('type','text'),'searchable'=>$r->boolean('searchable'),'position'=>$r->integer('position'),'options'=>$r->filled('options')?preg_split('/\R/',trim($r->options)):null]);return back()->with('ok','Поле добавлено');}
 public function settings(Request $r){if($r->isMethod('post')){foreach($r->input('settings',[]) as $k=>$v)AppSetting::updateOrCreate(['key'=>$k],['value'=>$v]);return back()->with('ok','Настройки сохранены');}return view('admin.legacy.settings',['settings'=>AppSetting::pluck('value','key')]);}
 public function content(){return view('admin.legacy.content',['news'=>News::latest('published_at')->get(),'testimonials'=>Testimonial::latest('dated_at')->get()]);}
 public function contentStore(Request $r){$d=$r->validate(['kind'=>'required|in:news,testimonial','title'=>'nullable|max:255','author'=>'nullable|max:255','body'=>'required','image'=>'nullable|max:500','date'=>'nullable|date']);if($d['kind']==='news')News::create(['title'=>$d['title']?:'Новость','body'=>$d['body'],'image'=>$d['image']??null,'published_at'=>$d['date']??now()->toDateString()]);else Testimonial::create(['author'=>$d['author']?:'Без имени','body'=>$d['body'],'image'=>$d['image']??null,'dated_at'=>$d['date']??now()->toDateString()]);return back()->with('ok','Материал опубликован');}
 public function reports(Request $r){$programs=Program::orderBy('title')->get();$enrollments=Enrollment::with('user','program')->when($r->program_id,fn($q,$v)=>$q->where('program_id',$v))->get();return view('admin.legacy.reports',compact('programs','enrollments'));}
 public function quizOverride(Request $r,AuditService $audit){$d=$r->validate(['quiz_id'=>'required|exists:quizzes,id','user_id'=>'required|exists:users,id','available_from'=>'nullable|date','available_until'=>'nullable|date','attempt_limit'=>'nullable|integer|min:1','reason'=>'nullable']);$old=QuizUserOverride::where(['quiz_id'=>$d['quiz_id'],'user_id'=>$d['user_id']])->first();$x=QuizUserOverride::updateOrCreate(['quiz_id'=>$d['quiz_id'],'user_id'=>$d['user_id']],$d+['changed_by'=>auth()->id()]);$audit->write('quiz_override',$x,$old?->toArray()??[],$x->toArray());return back()->with('ok','Персональные условия теста сохранены');}
 public function audit(){return view('admin.legacy.audit',['items'=>AuditLog::latest()->paginate(100)]);}
}
