<?php
namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\{Quiz,QuizAssignment,QuizAttempt,QuizUserOverride,Program,LearningSection,LearningSectionProgress,LegacyQuizXmlResult,User};
use App\Services\{AuditService,QuizReportingService};
use Illuminate\Http\Request;

class QuizAdminController extends Controller
{
 public function index(Request $r){$q=QuizAssignment::with('quiz','program','learningSection')->withCount('attempts');if($r->filled('program_id'))$q->where('program_id',$r->integer('program_id'));return view('admin.quizzes.index',['items'=>$q->latest()->paginate(40)->withQueryString(),'programs'=>Program::orderBy('title')->get(),'sections'=>LearningSection::orderBy('program_id')->orderBy('position')->get(),'quizzes'=>Quiz::orderBy('title')->get(),'users'=>User::where('role','student')->orderBy('full_name')->limit(1000)->get(['id','full_name','login'])]);}
 public function store(Request $r,AuditService $audit){$a=QuizAssignment::create($this->data($r));$audit->write('quiz.assignment.created',$a,[],$a->toArray());return back()->with('ok','Назначение теста создано. Банк вопросов не изменялся.');}
 public function update(Request $r,QuizAssignment $assignment,AuditService $audit){$before=$assignment->toArray();$assignment->update($this->data($r));$audit->write('quiz.assignment.updated',$assignment,$before,$assignment->fresh()->toArray());return back()->with('ok','Условия тестирования сохранены.');}
 public function override(Request $r,QuizAssignment $assignment,AuditService $audit){$d=$r->validate(['user_id'=>'required|exists:users,id','available_from'=>'nullable|date','available_until'=>'nullable|date|after_or_equal:available_from','attempt_limit'=>'nullable|integer|min:0|max:1000','is_active_override'=>'nullable|boolean','reason'=>'nullable|string|max:2000']);$old=QuizUserOverride::where('quiz_assignment_id',$assignment->id)->where('user_id',$d['user_id'])->first();$o=QuizUserOverride::updateOrCreate(['quiz_assignment_id'=>$assignment->id,'user_id'=>$d['user_id']],$d+['quiz_id'=>$assignment->quiz_id,'changed_by'=>auth()->id()]);$audit->write('quiz.override.saved',$o,$old?->toArray()??[],$o->fresh()->toArray());return back()->with('ok','Персональные условия сохранены.');}
 public function attempts(Request $r){$q=QuizAttempt::with('quiz','user','adjustedBy','assignment.program');if($r->filled('program_id'))$q->whereHas('assignment',fn($x)=>$x->where('program_id',$r->integer('program_id')));if($r->filled('assignment_id'))$q->where('quiz_assignment_id',$r->integer('assignment_id'));if($r->filled('user_id'))$q->where('user_id',$r->integer('user_id'));return view('admin.quizzes.attempts',['items'=>$q->latest('finished_at')->paginate(60)->withQueryString(),'programs'=>Program::orderBy('title')->get(),'assignments'=>QuizAssignment::orderBy('title')->get()]);}
 public function adjust(Request $r,QuizAttempt $attempt,AuditService $audit){$d=$r->validate(['score'=>'required|numeric|min:0','percent'=>'required|numeric|min:0|max:100','passed'=>'nullable|boolean','admin_comment'=>'required|string|max:3000']);$before=$attempt->toArray();$attempt->update(['original_score'=>$attempt->original_score??$attempt->score,'original_percent'=>$attempt->original_percent??$attempt->percent,'score'=>$d['score'],'percent'=>$d['percent'],'passed'=>$r->boolean('passed'),'admin_comment'=>$d['admin_comment'],'adjusted_by'=>auth()->id(),'adjusted_at'=>now()]);$audit->write('quiz.attempt.adjusted',$attempt,$before,$attempt->fresh()->toArray());return back()->with('ok','Результат скорректирован и записан в журнал аудита.');}
 public function report(Request $r,QuizReportingService $reporting){$programId=$r->integer('program_id');$mode=in_array($r->get('mode'),['latest','best'],true)?$r->get('mode'):'latest';$data=$programId?$reporting->build($programId,$mode):['program'=>null,'assignments'=>collect(),'rows'=>collect(),'summary'=>[],'mode'=>$mode,'thresholds'=>$reporting->thresholds()];return view('admin.quizzes.report',$data+['programId'=>$programId,'programs'=>Program::orderBy('title')->get()]);}
 public function printReport(Request $r,QuizReportingService $reporting){$programId=$r->integer('program_id');abort_unless($programId,404);$mode=in_array($r->get('mode'),['latest','best'],true)?$r->get('mode'):'latest';$format=$r->get('format')==='grades'?'grades':'percent';return view('admin.quizzes.print',$reporting->build($programId,$mode)+compact('format'));}
 public function studentReport(Request $r,Program $program,User $user,QuizReportingService $reporting){$mode=in_array($r->get('mode'),['latest','best'],true)?$r->get('mode'):'latest';return view('admin.quizzes.student',$reporting->student($program->id,$user->id,$mode));}
 public function nmoState(Request $r){$q=LearningSectionProgress::with('user','section','program');if($r->filled('program_id'))$q->where('program_id',$r->integer('program_id'));if($r->filled('user_id'))$q->where('user_id',$r->integer('user_id'));return view('admin.quizzes.nmo-state',['items'=>$q->latest('legacy_date')->paginate(80)->withQueryString(),'programs'=>Program::orderBy('title')->get(),'xml'=>LegacyQuizXmlResult::latest()->paginate(30,['*'],'xmlpage')]);}
 public function updateNmoState(Request $r,LearningSectionProgress $progress,AuditService $audit){$d=$r->validate(['completed'=>'nullable|boolean','sp'=>'nullable|integer','psp'=>'nullable|integer','pop'=>'nullable|string|max:20','legacy_date'=>'nullable|date']);$before=$progress->toArray();$progress->update(['completed'=>$r->boolean('completed'),'sp'=>$d['sp']??null,'psp'=>$d['psp']??null,'pop'=>$d['pop']??null,'legacy_date'=>$d['legacy_date']??null]);$audit->write('nmo.section-progress.adjusted',$progress,$before,$progress->fresh()->toArray());return back()->with('ok','Состояние раздела НМО сохранено.');}
 private function data(Request $r):array{return $r->validate(['quiz_id'=>'required|exists:quizzes,id','program_id'=>'required|exists:programs,id','learning_section_id'=>'nullable|exists:learning_sections,id','title'=>'required|string|max:255','description'=>'nullable|string','pass_percent'=>'required|integer|min:0|max:100','attempt_limit'=>'nullable|integer|min:1|max:1000','available_from'=>'nullable|date','available_until'=>'nullable|date|after_or_equal:available_from'])+['is_active'=>$r->boolean('is_active'),'is_required'=>$r->boolean('is_required')];}
}
