@extends('layouts.app')
@section('title',$enrollment->program->title)
@section('page-title','Моя программа')
@section('content')
<div class="page-heading"><div><a class="back-link" href="{{ route('dashboard') }}">← Личный кабинет</a><h1>{{ $enrollment->program->title }}</h1><p>{{ $enrollment->program->description }}</p></div><div class="badge-soft">{{ number_format((float)$enrollment->progress_percent,0) }}% пройдено</div></div>
<div class="stats-grid"><div class="stat-card"><span>Разделов</span><strong>{{ $sections->count() }}</strong></div><div class="stat-card"><span>Тестов</span><strong>{{ $quizzes->count() }}</strong></div><div class="stat-card"><span>Практических работ</span><strong>{{ $practice->count() }}</strong></div><div class="stat-card"><span>Документов</span><strong>{{ $documents->count() }}</strong></div></div>
<div class="panel mt-4"><div class="panel-head"><h2>Учебные разделы</h2></div>@forelse($sections as $section) @php($sp=$sectionProgress->get($section->id)) <div class="list-row"><div><strong>{{ $section->title }}</strong><small>{{ $section->is_required?'Обязательный':'Дополнительный' }} · {{ number_format((float)($sp?->progress_percent??0),0) }}%</small></div>@if($section->can_open)<a class="btn btn-sm btn-primary" href="{{ route('learning.show',$section) }}">Открыть</a>@else<span class="status blocked">Закрыт</span>@endif</div>@empty<p class="empty">Учебных разделов нет.</p>@endforelse</div>
<div class="row g-4 mt-1"><div class="col-lg-6"><div class="panel"><div class="panel-head"><h2>Тестирование</h2><a href="{{ route('quizzes.index') }}">Все тесты</a></div>@forelse($quizzes as $quiz) @php($attempt=$quizAttempts->get($quiz->id)?->first()) <div class="list-row"><div><strong>{{ $quiz->title }}</strong><small>{{ $quiz->is_required?'Обязательный':'Дополнительный' }}@if($attempt) · последняя попытка {{ number_format($attempt->percent,0) }}%@endif</small></div><a class="btn btn-sm btn-primary" href="{{ route('quizzes.show',$quiz) }}">{{ $attempt?'Повторить':'Пройти' }}</a></div>@empty<p class="empty">Тестов нет.</p>@endforelse</div></div>
<div class="col-lg-6"><div class="panel"><div class="panel-head"><h2>Практика</h2><a href="{{ route('practice.index') }}">Все задания</a></div>@forelse($practice as $a) @php($s=$submissions->get($a->id)) <div class="list-row"><div><strong>{{ $a->title }}</strong><small>{{ $s?->status ?: 'не отправлено' }}@if($a->ends_at) · до {{ $a->ends_at->format('d.m.Y') }}@endif</small></div><a class="btn btn-sm btn-primary" href="{{ route('practice.index') }}">Открыть</a></div>@empty<p class="empty">Практических заданий нет.</p>@endforelse</div></div></div>
@if($finalWorks->isNotEmpty())<div class="panel mt-4"><div class="panel-head"><h2>Итоговая работа</h2></div>@foreach($finalWorks as $work)<div class="list-row"><div><strong>{{ $work->title ?? 'Итоговая работа' }}</strong><small>{{ $work->review_comment }}</small></div><span class="status {{ $work->status }}">{{ $work->status }}</span></div>@endforeach</div>@endif
@if($documents->isNotEmpty())<div class="panel mt-4"><div class="panel-head"><h2>Документы об обучении</h2><a href="{{ route('documents.index') }}">Все документы</a></div>@foreach($documents as $document)<div class="list-row"><div><strong>{{ $document->title ?? $document->type ?? 'Документ' }}</strong><small>{{ optional($document->issued_at)->format('d.m.Y') }}</small></div>@if($document->file_path)<a href="{{ Storage::url($document->file_path) }}">Скачать</a>@endif</div>@endforeach</div>@endif
@endsection
