@extends('layouts.app')
@section('title','Тестирование: банк, назначения и доступ')
@section('content')
<div class="card"><h3>Банк тестов</h3><p>Тестов: <b>{{$bank['total']}}</b>; распознано в Laravel-вопросы: <b>{{$bank['parsed']}}</b>; только legacy-пакет: <b>{{$bank['package_only']}}</b>; отсутствует/ошибка: <b>{{$bank['missing']}}</b>; нормализованных вопросов: <b>{{$bank['questions']}}</b>.</p><div style="overflow:auto"><table><tr><th>ID</th><th>Тест</th><th>Legacy</th><th>Вопросов</th><th>Статус импорта</th><th>Пакет</th><th>Ответы</th></tr>@foreach($quizzes as $q)<tr><td>{{$q->id}}</td><td>{{$q->title}}</td><td>{{$q->legacy_id}}</td><td>{{$q->questions_count}} / {{$q->legacy_question_count ?? '—'}}</td><td>{{$q->import_status ?? 'native'}} @if($q->import_message)<br><small>{{$q->import_message}}</small>@endif</td><td><small>{{$q->legacy_archive_path ?? $q->legacy_path ?? '—'}}</small></td><td><small>{{$q->legacy_answer_archive_path ?? $q->legacy_answer_file ?? '—'}}</small></td></tr>@endforeach</table></div></div>
<div class="card"><p>Ниже редактируется назначение теста программе и персональные условия доступа.</p><a class="btn" href="{{route('admin.quizzes.attempts')}}">Результаты и корректировки</a> <a class="btn gray" href="{{route('admin.quizzes.report')}}">Отчёт по программе</a></div>
<datalist id="students">@foreach($users as $u)<option value="{{$u->id}}">{{$u->full_name}} — {{$u->login}}</option>@endforeach</datalist>
<div class="card"><h3>Новое назначение</h3><form method="post" action="{{route('admin.quizzes.store')}}">@csrf<div class="grid"><div><label>Тест</label><select name="quiz_id" required>@foreach($quizzes as $q)<option value="{{$q->id}}">{{$q->title}}</option>@endforeach</select></div><div><label>Программа</label><select name="program_id" required>@foreach($programs as $p)<option value="{{$p->id}}">{{$p->title}}</option>@endforeach</select></div><div><label>Раздел</label><select name="learning_section_id"><option value="">Без раздела</option>@foreach($sections as $s)<option value="{{$s->id}}">#{{$s->program_id}} {{$s->title}}</option>@endforeach</select></div><div><label>Название для программы</label><input name="title" required value="Базовый"></div><div><label>Проходной %</label><input type="number" name="pass_percent" value="70" min="0" max="100"></div><div><label>Попыток</label><input type="number" name="attempt_limit" min="1"></div><div><label>Открыть с</label><input type="datetime-local" name="available_from"></div><div><label>Закрыть</label><input type="datetime-local" name="available_until"></div></div><label><input style="width:auto" type="checkbox" name="is_active" value="1" checked> Активно</label><label><input style="width:auto" type="checkbox" name="is_required" value="1"> Обязательно</label><button class="btn">Создать назначение</button></form></div>
@foreach($items as $a)<div class="card"><h3>{{$a->title}} <small>— {{$a->quiz?->title}}</small></h3><form method="post" action="{{route('admin.quizzes.update',$a)}}">@csrf @method('PUT')<div class="grid"><div><label>Тест</label><select name="quiz_id">@foreach($quizzes as $q)<option value="{{$q->id}}" @selected($a->quiz_id==$q->id)>{{$q->title}}</option>@endforeach</select></div><div><label>Программа</label><select name="program_id">@foreach($programs as $p)<option value="{{$p->id}}" @selected($a->program_id==$p->id)>{{$p->title}}</option>@endforeach</select></div><div><label>Раздел</label><select name="learning_section_id"><option value="">Без раздела</option>@foreach($sections as $s)<option value="{{$s->id}}" @selected($a->learning_section_id==$s->id)>#{{$s->program_id}} {{$s->title}}</option>@endforeach</select></div><div><label>Название</label><input name="title" value="{{$a->title}}"></div><div><label>Проходной %</label><input type="number" name="pass_percent" value="{{$a->pass_percent}}"></div><div><label>Лимит попыток</label><input type="number" name="attempt_limit" value="{{$a->attempt_limit}}"></div><div><label>С</label><input type="datetime-local" name="available_from" value="{{$a->available_from?->format('Y-m-d\TH:i')}}"></div><div><label>До</label><input type="datetime-local" name="available_until" value="{{$a->available_until?->format('Y-m-d\TH:i')}}"></div></div><label><input style="width:auto" type="checkbox" name="is_active" value="1" @checked($a->is_active)> Активно</label><label><input style="width:auto" type="checkbox" name="is_required" value="1" @checked($a->is_required)> Обязательно</label><button class="btn">Сохранить</button> <span>Попыток: {{$a->attempts_count}}</span></form><hr><form method="post" action="{{route('admin.quizzes.override',$a)}}">@csrf<div class="grid"><div><label>Слушатель</label><input type="number" list="students" name="user_id" required></div><div><label>Персонально с</label><input type="datetime-local" name="available_from"></div><div><label>Персонально до</label><input type="datetime-local" name="available_until"></div><div><label>Персональный лимит</label><input type="number" name="attempt_limit" min="0"></div><div><label>Причина</label><input name="reason"></div></div><button class="btn gray">Сохранить персональные условия</button></form></div>@endforeach
{{$items->links()}}
@endsection
