@extends('layouts.app')
@section('title','Отчёт по тестированию')
@section('content')
<div class="card"><form method="get" class="grid"><div><label>Программа</label><select name="program_id"><option value="0">Выберите программу</option>@foreach($programs as $p)<option value="{{$p->id}}" @selected($programId==$p->id)>{{$p->title}}</option>@endforeach</select></div><div><label>Результат попыток</label><select name="mode"><option value="latest" @selected($mode==='latest')>Последняя попытка (legacy)</option><option value="best" @selected($mode==='best')>Лучшая попытка</option></select></div><div style="align-self:end"><button class="btn">Показать</button></div></form></div>
@if($program)
<div class="card"><b>{{$program->title}}</b><div class="grid" style="margin-top:12px"><div>Слушателей: <b>{{$summary['students']}}</b></div><div>Полностью завершили: <b>{{$summary['fully_completed']}}</b></div><div>Пройдено тестов: <b>{{$summary['passed_cells']}}</b></div><div>Не пройдено: <b>{{$summary['failed_cells']}}</b></div><div>Нет результата: <b>{{$summary['missing_cells']}}</b></div></div><p><small>Пороги оценок: 3 — от {{$thresholds[3]}}%, 4 — от {{$thresholds[4]}}%, 5 — от {{$thresholds[5]}}%.</small></p><a class="btn" target="_blank" href="{{route('admin.quizzes.report.print',['program_id'=>$program->id,'mode'=>$mode,'format'=>'percent'])}}">Печать в процентах</a> <a class="btn gray" target="_blank" href="{{route('admin.quizzes.report.print',['program_id'=>$program->id,'mode'=>$mode,'format'=>'grades'])}}">Печать в оценках</a></div>
<div class="card" style="overflow:auto"><table><tr><th>Слушатель</th>@foreach($assignments as $a)<th>{{$a->title}}</th>@endforeach<th>Итог</th><th>Статус</th></tr>@foreach($rows as $row)<tr><td><a href="{{route('admin.quizzes.report.student',[$program,$row['user'],'mode'=>$mode])}}">{{$row['user']->full_name}}</a></td>@foreach($assignments as $a)@php($cell=$row['cells'][$a->id])<td>@if($cell['attempt']){{$cell['percent']}}% / {{$cell['grade']}}<br><small>{{$cell['attempt']->passed?'пройден':'не пройден'}}, попыток {{$cell['attempts']}}</small>@else — @endif</td>@endforeach<td>@if($row['average']!==null)<b>{{$row['average']}}%</b> / {{$row['grade']}}@else — @endif</td><td>@if($row['missing']===0&&$row['failed']===0)<b>Все тесты пройдены</b>@elseif($row['failed']>0)Не пройдено: {{$row['failed']}}@else Нет результатов: {{$row['missing']}}@endif</td></tr>@endforeach</table></div>
@endif
@endsection
