@extends('layouts.app')
@section('title','Обзор')
@section('page-title','Обзор обучения')
@section('content')
<div class="hero-panel"><div><span class="eyebrow">Личный кабинет</span><h1>{{ $user->full_name }}</h1><p>Текущие программы, учебные разделы, тесты, практика, документы и прогресс обучения.</p></div><div class="progress-ring"><strong>{{ number_format($avgProgress,0) }}%</strong><span>средний прогресс</span></div></div>
<div class="stats-grid"><div class="stat-card"><span>Программ</span><strong>{{ $enrollments->count() }}</strong></div><div class="stat-card"><span>Активных</span><strong>{{ $enrollments->where('status','active')->count() }}</strong></div><div class="stat-card"><span>Завершено</span><strong>{{ $enrollments->where('status','completed')->count() }}</strong></div><div class="stat-card"><span>Последних тестов</span><strong>{{ $lastAttempts->count() }}</strong></div></div>
<div class="row g-4 mt-1"><div class="col-lg-8"><div class="panel"><div class="panel-head"><h2>Мои программы</h2><a href="{{ route('learning.index') }}">Все разделы</a></div>
@forelse($enrollments as $e)<a class="list-row" href="{{ $e->status==='active' ? route('programs.show',$e) : 'javascript:void(0)' }}"><div style="flex:1"><strong>{{ $e->program->title }}</strong><small>{{ $e->group?->name ?: 'Без группы' }} · {{ $e->status }}</small><div style="height:7px;background:#e9ecef;border-radius:5px;margin-top:8px;overflow:hidden"><div style="height:100%;width:{{ min(100,(float)$e->progress_percent) }}%;background:currentColor"></div></div></div><strong>{{ number_format((float)$e->progress_percent,0) }}%</strong></a>@empty<p class="empty">Нет назначенных программ.</p>@endforelse
</div></div><div class="col-lg-4"><div class="panel"><div class="panel-head"><h2>Объявления</h2></div>@forelse($announcements as $a)<article class="announcement"><strong>{{ $a->title }}</strong><p>{{ \Illuminate\Support\Str::limit(strip_tags($a->body),120) }}</p><small>{{ optional($a->published_at)->format('d.m.Y') }}</small></article>@empty<p class="empty">Новых объявлений нет.</p>@endforelse</div></div></div>
@if($lastAttempts->isNotEmpty())<div class="panel mt-4"><div class="panel-head"><h2>Последние тесты</h2><a href="{{ route('quizzes.index') }}">Все тесты</a></div>@foreach($lastAttempts as $attempt)<div class="list-row"><div><strong>{{ $attempt->assignment?->title ?: $attempt->quiz?->title ?: 'Тест' }}</strong><small>{{ optional($attempt->finished_at)->format('d.m.Y H:i') }}</small></div><span class="status {{ $attempt->passed?'completed':'blocked' }}">{{ number_format($attempt->percent,0) }}%</span></div>@endforeach</div>@endif
@endsection
