<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AuthController,DashboardController,LearningController,QuizController,PracticeController,DocumentController,ForumController};
use App\Http\Controllers\Admin\{DashboardController as AdminDashboard,ProgramController as AdminPrograms,UserController as AdminUsers,EnrollmentController as AdminEnrollments,SectionController as AdminSections,ReviewController as AdminReview,GroupController as AdminGroups,DocumentAdminController as AdminDocuments,AnnouncementController as AdminAnnouncements,LegacyAdminController,BulkUserController,ContentAdminController,ArchiveAdminController,PermissionController,QuizAdminController};
use App\Http\Controllers\Curator\DashboardController as CuratorDashboard;

Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'showLogin'])->name('login');Route::post('/login',[AuthController::class,'login'])->name('login.perform');});
Route::post('/logout',[AuthController::class,'logout'])->middleware('auth')->name('logout');
Route::middleware('auth')->group(function(){
 Route::get('/',[DashboardController::class,'index'])->name('dashboard');Route::get('/learning',[LearningController::class,'index'])->name('learning.index');Route::get('/learning/{section}',[LearningController::class,'show'])->name('learning.show');
 Route::get('/quizzes',[QuizController::class,'index'])->name('quizzes.index');Route::get('/quizzes/{assignment}',[QuizController::class,'show'])->name('quizzes.show');Route::post('/quizzes/{assignment}',[QuizController::class,'submit'])->name('quizzes.submit');
 Route::get('/practice',[PracticeController::class,'index'])->name('practice.index');Route::get('/documents',[DocumentController::class,'index'])->name('documents.index');Route::get('/forum',[ForumController::class,'index'])->name('forum.index');
 Route::prefix('curator')->name('curator.')->middleware('role:curator,admin')->group(function(){Route::get('/',[CuratorDashboard::class,'index'])->name('dashboard');Route::get('/review',[AdminReview::class,'index'])->name('review');Route::patch('/review/submission/{submission}',[AdminReview::class,'submission'])->name('review.submission');Route::patch('/review/final/{finalWork}',[AdminReview::class,'finalWork'])->name('review.final');});
 Route::prefix('admin')->name('admin.')->middleware('role:admin')->group(function(){
  Route::get('/',[AdminDashboard::class,'index'])->name('dashboard');Route::resource('programs',AdminPrograms::class)->except('show');Route::resource('users',AdminUsers::class)->except('show');Route::resource('groups',AdminGroups::class)->only(['index','store','update','destroy']);Route::get('/enrollments',[AdminEnrollments::class,'index'])->name('enrollments.index');Route::patch('/enrollments/{enrollment}',[AdminEnrollments::class,'update'])->name('enrollments.update');Route::post('/enrollments/{enrollment}/complete',[AdminEnrollments::class,'complete'])->name('enrollments.complete');Route::resource('sections',AdminSections::class)->only(['index','store','update','destroy']);Route::get('/review',[AdminReview::class,'index'])->name('review.index');Route::patch('/review/submission/{submission}',[AdminReview::class,'submission'])->name('review.submission');Route::patch('/review/final/{finalWork}',[AdminReview::class,'finalWork'])->name('review.final');Route::resource('documents',AdminDocuments::class)->only(['index','store','destroy']);Route::resource('announcements',AdminAnnouncements::class)->only(['index','store','update','destroy']);
  Route::get('/quizzes',[QuizAdminController::class,'index'])->name('quizzes.index');Route::post('/quizzes',[QuizAdminController::class,'store'])->name('quizzes.store');Route::put('/quizzes/{assignment}',[QuizAdminController::class,'update'])->name('quizzes.update');Route::post('/quizzes/{assignment}/override',[QuizAdminController::class,'override'])->name('quizzes.override');Route::get('/quiz-attempts',[QuizAdminController::class,'attempts'])->name('quizzes.attempts');Route::patch('/quiz-attempts/{attempt}',[QuizAdminController::class,'adjust'])->name('quizzes.attempt-adjust');Route::get('/quiz-report',[QuizAdminController::class,'report'])->name('quizzes.report');
  Route::prefix('legacy')->name('legacy.')->group(function(){Route::get('/',[LegacyAdminController::class,'index'])->name('index');Route::get('/references',[LegacyAdminController::class,'references'])->name('references');Route::post('/references',[LegacyAdminController::class,'referenceStore']);Route::get('/resources',[LegacyAdminController::class,'resources'])->name('resources');Route::post('/resources',[LegacyAdminController::class,'resourceStore']);Route::get('/practice',[LegacyAdminController::class,'practice'])->name('practice');Route::post('/practice',[LegacyAdminController::class,'practiceStore']);Route::get('/finals',[LegacyAdminController::class,'finals'])->name('finals');Route::post('/finals',[LegacyAdminController::class,'finalStore']);Route::get('/instructors',[LegacyAdminController::class,'instructors'])->name('instructors');Route::post('/instructors',[LegacyAdminController::class,'instructorStore']);Route::post('/instructor-slot',[LegacyAdminController::class,'slotStore'])->name('instructor-slot');Route::get('/surveys',[LegacyAdminController::class,'surveys'])->name('surveys');Route::post('/surveys',[LegacyAdminController::class,'surveyStore']);Route::get('/surveys/{survey}/report',[LegacyAdminController::class,'surveyReport'])->name('survey-report');Route::get('/custom-fields',[LegacyAdminController::class,'customFields'])->name('custom-fields');Route::post('/custom-fields',[LegacyAdminController::class,'customFieldStore']);Route::match(['get','post'],'/settings',[LegacyAdminController::class,'settings'])->name('settings');Route::get('/content',[LegacyAdminController::class,'content'])->name('content');Route::post('/content',[LegacyAdminController::class,'contentStore']);Route::get('/reports',[LegacyAdminController::class,'reports'])->name('reports');Route::post('/quiz-override',[LegacyAdminController::class,'quizOverride'])->name('quiz-override');Route::get('/audit',[LegacyAdminController::class,'audit'])->name('audit');Route::get('/learning-content',[ContentAdminController::class,'index'])->name('learning-content');Route::post('/learning-content/section',[ContentAdminController::class,'section'])->name('content-section');Route::post('/learning-content/item',[ContentAdminController::class,'item'])->name('content-item');Route::patch('/learning-content/item/{item}',[ContentAdminController::class,'update'])->name('content-item-update');Route::post('/learning-content/section/{section}/copy',[ContentAdminController::class,'copySection'])->name('section-copy');Route::post('/learning-content/item/{item}/copy',[ContentAdminController::class,'copyItem'])->name('item-copy');Route::get('/archive',[ArchiveAdminController::class,'index'])->name('archive');Route::post('/archive/import',[ArchiveAdminController::class,'import'])->name('archive-import');Route::get('/permissions',[PermissionController::class,'index'])->name('permissions');Route::post('/permissions',[PermissionController::class,'store']);});
  Route::post('/users/bulk',[BulkUserController::class,'create'])->name('users.bulk');Route::post('/users/transfer',[BulkUserController::class,'transfer'])->name('users.transfer');Route::patch('/enrollments/{enrollment}/state',[BulkUserController::class,'state'])->name('enrollments.state');Route::post('/users/{user}/confirm',[BulkUserController::class,'confirm'])->name('users.confirm');Route::put('/users/{user}/address',[BulkUserController::class,'address'])->name('users.address');
 });
});