<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{AuthController,DashboardController,LearningController,QuizController,PracticeController,DocumentController,ForumController,PublicSiteController,CourseRegistrationController};
use App\Http\Controllers\Admin\{DashboardController as AdminDashboard,ProgramController as AdminPrograms,ProgramTypeController as AdminProgramTypes,UserController as AdminUsers,EnrollmentController as AdminEnrollments,SectionController as AdminSections,ReviewController as AdminReview,GroupController as AdminGroups,DocumentAdminController as AdminDocuments,AnnouncementController as AdminAnnouncements,LegacyAdminController,BulkUserController,ContentAdminController,ArchiveAdminController,PermissionController,QuizAdminController};
use App\Http\Controllers\Curator\DashboardController as CuratorDashboard;
use App\Http\Controllers\Curator\LegacyCabinetController as CuratorLegacy;

Route::get('/',[PublicSiteController::class,'home'])->name('home');
Route::get('/courses',[PublicSiteController::class,'programs'])->name('public.programs');
Route::get('/courses/{program}/register',[CourseRegistrationController::class,'create'])->middleware('guest')->name('public.program.register');
Route::post('/courses/{program}/register',[CourseRegistrationController::class,'store'])->middleware('guest')->name('public.program.register.store');
Route::get('/registration/sent/{user}',[CourseRegistrationController::class,'sent'])->middleware('guest')->name('public.registration.sent');
Route::get('/registration/verify/{user}',[CourseRegistrationController::class,'verify'])->middleware('guest')->name('public.registration.verify');
Route::get('/courses/{program}',[PublicSiteController::class,'program'])->name('public.program');

Route::middleware('guest')->group(function(){Route::get('/login',[AuthController::class,'showLogin'])->name('login');Route::post('/login',[AuthController::class,'login'])->name('login.perform');});
Route::post('/logout',[AuthController::class,'logout'])->middleware('auth')->name('logout');
Route::middleware('auth')->group(function(){
 Route::get('/cabinet',[DashboardController::class,'index'])->name('dashboard');Route::get('/learning',[LearningController::class,'index'])->name('learning.index');Route::get('/learning/{section}',[LearningController::class,'show'])->name('learning.show');
 Route::get('/quizzes',[QuizController::class,'index'])->name('quizzes.index');Route::get('/quizzes/{assignment}',[QuizController::class,'show'])->name('quizzes.show');Route::post('/quizzes/{assignment}',[QuizController::class,'submit'])->name('quizzes.submit');
 Route::get('/practice',[PracticeController::class,'index'])->name('practice.index');Route::get('/documents',[DocumentController::class,'index'])->name('documents.index');Route::get('/forum',[ForumController::class,'index'])->name('forum.index');
 Route::prefix('curator')->name('curator.')->middleware('role:curator,admin')->group(function(){
  Route::get('/',[CuratorDashboard::class,'index'])->name('dashboard');
  Route::get('/students',[CuratorLegacy::class,'students'])->name('students');Route::get('/students/{enrollment}',[CuratorLegacy::class,'student'])->name('student');
  Route::get('/review',[AdminReview::class,'index'])->name('review');Route::patch('/review/submission/{submission}',[AdminReview::class,'submission'])->name('review.submission');Route::patch('/review/final/{finalWork}',[AdminReview::class,'finalWork'])->name('review.final');
  Route::get('/attendance',[CuratorLegacy::class,'attendance'])->name('attendance');Route::get('/practice',[CuratorLegacy::class,'practice'])->name('practice');Route::get('/files',[CuratorLegacy::class,'files'])->name('files');
  Route::get('/content',[CuratorLegacy::class,'content'])->name('content');Route::post('/content/{section}',[CuratorLegacy::class,'storeContent'])->name('content.store');Route::patch('/content/{item}',[CuratorLegacy::class,'updateContent'])->name('content.update');
  Route::get('/documents',[CuratorLegacy::class,'documents'])->name('documents');Route::get('/legacy-file/{record}',[CuratorLegacy::class,'downloadLegacy'])->name('legacy.download');
  Route::get('/announcements',[CuratorLegacy::class,'announcements'])->name('announcements');Route::post('/announcements',[CuratorLegacy::class,'storeAnnouncement'])->name('announcements.store');
  Route::get('/logins',[CuratorLegacy::class,'logins'])->name('logins');Route::get('/surveys',[CuratorLegacy::class,'surveys'])->name('surveys');
  Route::get('/statistics',[CuratorLegacy::class,'statistics'])->name('statistics');Route::get('/tables',[CuratorLegacy::class,'tables'])->name('tables');
  Route::get('/groups',[CuratorLegacy::class,'groups'])->name('groups');Route::patch('/groups/{enrollment}',[CuratorLegacy::class,'updateGroup'])->name('groups.update');
 });
 Route::prefix('admin')->name('admin.')->middleware('role:admin')->group(function(){
  Route::get('/',[AdminDashboard::class,'index'])->name('dashboard');
  Route::get('/nmo',[ContentAdminController::class,'index'])->name('nmo.index');
  Route::resource('program-types',AdminProgramTypes::class)->only(['index','store','update','destroy']);Route::resource('programs',AdminPrograms::class)->except('show');Route::resource('users',AdminUsers::class)->except('show');Route::resource('groups',AdminGroups::class)->only(['index','store','update','destroy']);Route::get('/enrollments',[AdminEnrollments::class,'index'])->name('enrollments.index');Route::patch('/enrollments/{enrollment}',[AdminEnrollments::class,'update'])->name('enrollments.update');Route::post('/enrollments/{enrollment}/complete',[AdminEnrollments::class,'complete'])->name('enrollments.complete');Route::resource('sections',AdminSections::class)->only(['index','store','update','destroy']);Route::get('/review',[AdminReview::class,'index'])->name('review.index');Route::patch('/review/submission/{submission}',[AdminReview::class,'submission'])->name('review.submission');Route::patch('/review/final/{finalWork}',[AdminReview::class,'finalWork'])->name('review.final');Route::resource('documents',AdminDocuments::class)->only(['index','store','destroy']);Route::resource('announcements',AdminAnnouncements::class)->only(['index','store','update','destroy']);
  Route::get('/quizzes',[QuizAdminController::class,'index'])->name('quizzes.index');Route::post('/quizzes',[QuizAdminController::class,'store'])->name('quizzes.store');Route::put('/quizzes/{assignment}',[QuizAdminController::class,'update'])->name('quizzes.update');Route::post('/quizzes/{assignment}/override',[QuizAdminController::class,'override'])->name('quizzes.override');Route::get('/quiz-attempts',[QuizAdminController::class,'attempts'])->name('quizzes.attempts');Route::patch('/quiz-attempts/{attempt}',[QuizAdminController::class,'adjust'])->name('quizzes.attempt-adjust');Route::get('/quiz-report',[QuizAdminController::class,'report'])->name('quizzes.report');Route::get('/quiz-report/print',[QuizAdminController::class,'printReport'])->name('quizzes.report.print');Route::get('/quiz-report/{program}/{user}',[QuizAdminController::class,'studentReport'])->name('quizzes.report.student');Route::get('/quiz-nmo-state',[QuizAdminController::class,'nmoState'])->name('quizzes.nmo-state');Route::patch('/quiz-nmo-state/{progress}',[QuizAdminController::class,'updateNmoState'])->name('quizzes.nmo-state.update');
  Route::prefix('legacy')->name('legacy.')->group(function(){Route::get('/',[LegacyAdminController::class,'index'])->name('index');Route::get('/references',[LegacyAdminController::class,'references'])->name('references');Route::post('/references',[LegacyAdminController::class,'referenceStore']);Route::get('/resources',[LegacyAdminController::class,'resources'])->name('resources');Route::post('/resources',[LegacyAdminController::class,'resourceStore']);Route::get('/practice',[LegacyAdminController::class,'practice'])->name('practice');Route::post('/practice',[LegacyAdminController::class,'practiceStore']);Route::get('/finals',[LegacyAdminController::class,'finals'])->name('finals');Route::post('/finals',[LegacyAdminController::class,'finalStore']);Route::get('/instructors',[LegacyAdminController::class,'instructors'])->name('instructors');Route::post('/instructors',[LegacyAdminController::class,'instructorStore']);Route::post('/instructor-slot',[LegacyAdminController::class,'slotStore'])->name('instructor-slot');Route::get('/surveys',[LegacyAdminController::class,'surveys'])->name('surveys');Route::post('/surveys',[LegacyAdminController::class,'surveyStore']);Route::get('/surveys/{survey}/report',[LegacyAdminController::class,'surveyReport'])->name('survey-report');Route::get('/custom-fields',[LegacyAdminController::class,'customFields'])->name('custom-fields');Route::post('/custom-fields',[LegacyAdminController::class,'customFieldStore']);Route::match(['get','post'],'/settings',[LegacyAdminController::class,'settings'])->name('settings');Route::get('/content',[LegacyAdminController::class,'content'])->name('content');Route::post('/content',[LegacyAdminController::class,'contentStore']);Route::get('/reports',[LegacyAdminController::class,'reports'])->name('reports');Route::post('/quiz-override',[LegacyAdminController::class,'quizOverride'])->name('quiz-override');Route::get('/audit',[LegacyAdminController::class,'audit'])->name('audit');Route::get('/learning-content',[ContentAdminController::class,'index'])->name('learning-content');Route::post('/learning-content/section',[ContentAdminController::class,'section'])->name('content-section');Route::post('/learning-content/item',[ContentAdminController::class,'item'])->name('content-item');Route::patch('/learning-content/item/{item}',[ContentAdminController::class,'update'])->name('content-item-update');Route::post('/learning-content/section/{section}/copy',[ContentAdminController::class,'copySection'])->name('section-copy');Route::post('/learning-content/item/{item}/copy',[ContentAdminController::class,'copyItem'])->name('item-copy');Route::get('/archive',[ArchiveAdminController::class,'index'])->name('archive');Route::post('/archive/import',[ArchiveAdminController::class,'import'])->name('archive-import');Route::get('/permissions',[PermissionController::class,'index'])->name('permissions');Route::post('/permissions',[PermissionController::class,'store']);});
  Route::post('/users/bulk',[BulkUserController::class,'create'])->name('users.bulk');Route::post('/users/transfer',[BulkUserController::class,'transfer'])->name('users.transfer');Route::patch('/enrollments/{enrollment}/state',[BulkUserController::class,'state'])->name('enrollments.state');Route::post('/users/{user}/confirm',[BulkUserController::class,'confirm'])->name('users.confirm');Route::put('/users/{user}/address',[BulkUserController::class,'address'])->name('users.address');
 });
});
